### ISSUE TITLE
打印文件名添加相对路径的方式

### ISSUE THREAD

**Issue by liao666brant** [Sean529/vscode-console-helper#19]
![image](https://user-images.githubusercontent.com/50171055/196074520-44c8b455-7f2d-43cb-a43e-bdcd414116b9.png)

如图，希望打印文件名的功能添加打印【相对路径的方式】，因为很多文件以index的方式命名，只显示文件名提示的信息不够，但是选择完整路径的话又显得累赘。

或者添加【文件+文件上级目录】的打印方式。

**Comment by liao666brant** [comment]
或者添加【文件+文件上级目录】的打印方式

**Comment by wChenonly** [comment]
我觉得可以，我比较常用
