### ISSUE TITLE
[feature]支持配置不需要一键移除的 console 类型

### ISSUE THREAD

**Issue by QuentinHsu** [Sean529/vscode-console-helper#22]
## Feature Request

因为插件目前是默认移除了所有的 console 类型
https://github.com/Sean529/vscode-console-helper/blob/8661d73257abb1b166fc2e2ff6cb0d4c6c168f7f/src/common/deleteAllLog/index.ts#L27

但实际的代码业务中，部分 console 类型是需要被保留的。比如 console.error。

直接一键移除所有 console 有点太彻底了。

## What does the proposed API examples?

英文逗号间隔的配置不需要被一键移除的 console（并且允许逗号后存在空格😜）

```
error, info, ...
```

**Comment by Sean529** [comment]
https://github.com/Sean529/vscode-console-helper/commit/d551adfcf4f4cbc77ce87a2fe7991e85e9355de6
